# Generated by Django 6.0.3 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_jobanalysis_description_jobanalysis_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalysis',
            name='analysis_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
